### PR TITLE
0.16.0 bug fixes

### PR DESCRIPTION
**Pull request by caspervanneck**

### CODE REVIEW

**Comment by TheAppleGamer** [comment]
Doesn't work

**Comment by TheAppleGamer** [comment]
You aren't too good at this either, not to mention your spelling!

**Comment by caspervanneck** [comment]
@TheAppleGamer  shut up

**Comment by caspervanneck** [comment]
krijg k...ker gast

**Comment by caspervanneck** [comment]
btw im 14 years old what do you tink

**Comment by caspervanneck** [comment]
but i try to fix it

**Comment by caspervanneck** [comment]
do you try it than !!!

**Pull request closed without merging**
