### PR TITLE
0.16.0 bug fix

### PR DESCRIPTION
**Pull request by Aericio**
If you try using FNPC in 0.16.0, there are errors.

### CODE REVIEW

**Comment by TheAppleGamer** [comment]
Creates leads coming from all NPC nametags

**Comment by Pogogo007** [comment]
Why are you remove No ai flag

**Comment by TheAppleGamer** [comment]
@Pogogo007 He should have changed it, but he removed it.

**Comment by Aericio** [comment]
huh, thats weird. it works fine for me though...

**Comment by Sandertv** [comment]
Oh whatever if it works I guess you dan keep it, just make sure you test it well.

**Comment by Aericio** [comment]
Oh, its DATA_FLAG_NO_AI now.

**Comment by NoHaxJustTryHqrd** [comment]
Do leads show lol

**Comment by TheAppleGamer** [comment]
Leads show for me

**Comment by NoHaxJustTryHqrd** [comment]
Fucking

**Comment by Aericio** [comment]
```
Warning: Division by zero in C:\Users\Aericio\Desktop\Minecraft PE\plugins\FNPC-master\src\FNPC\npc\NPC.php on line 176
Warning: Division by zero in C:\Users\Aericio\Desktop\Minecraft PE\plugins\FNPC-master\src\FNPC\npc\NPC.php on line 177
```
When I try to /fnpc add -_-

**Comment by NoHaxJustTryHqrd** [comment]
Gotta remove those stupid leads i swear

**Comment by TheAppleGamer** [comment]
He can't remove the leads I don't think

**Comment by NoHaxJustTryHqrd** [comment]
Delete leads from Genisys then

**Comment by Aericio** [comment]
I think that's the servercore fault for leads ?

**Comment by TheAppleGamer** [comment]
Genisys says that it's not them

**Comment by NoHaxJustTryHqrd** [comment]
It is Genisys LOL

**Comment by TheAppleGamer** [comment]
It cannot be because it would affect all entities that spawn but it doesn't

**Comment by NoHaxJustTryHqrd** [comment]
But its a bug with Genisys on certain entities

**Comment by TheAppleGamer** [comment]
Tested on all entities on Genisys

**Comment by NoHaxJustTryHqrd** [comment]
Look at flags there may be one to remove leads from it

**Comment by TheAppleGamer** [comment]
It's not gonna do anything, trust me I tried already.

**Comment by NoHaxJustTryHqrd** [comment]
What could cause the lead glitch then

**Comment by TheAppleGamer** [comment]
Not too sure, 0.16 changed quite a few things.

**Comment by NoHaxJustTryHqrd** [comment]
I saw a new flag called DATA_FLAG_LEASH might wanna check it out

**Comment by TheAppleGamer** [comment]
That's for animals

**Comment by Aericio** [comment]
DATA_LEAD and DATA_LEAD_HOLDER are still the same in 0.16.0

**Comment by NoHaxJustTryHqrd** [comment]
What to do to remove the stupid leashes then

**Comment by Aericio** [comment]
You deal with it.

**Comment by TheAppleGamer** [comment]
Actually those 2 are different

**Comment by NoHaxJustTryHqrd** [comment]
I already tried usinf some tags and none of them freaking work

**Comment by TheAppleGamer** [comment]
Lets just say the guy who opened this PR isn't a very friendly dev, and if he is a dev he isn't a very good one. I'll work on it in a bit.

**Comment by NoHaxJustTryHqrd** [comment]
I just found DATA_LEAD_HOLDER_EID

**Comment by TheAppleGamer** [comment]
That doesn't work either I already know that

**Comment by NoHaxJustTryHqrd** [comment]
DATA_FLAG_LEASHED

**Comment by TheAppleGamer** [comment]
It didn't take a genius to realize you aren't a good dev

**Pull request closed without merging**
